### ISSUE TITLE
Ви випустили модуль для версії 2.1 но по-факту він не робочий!

### ISSUE THREAD

**Issue by Stanislav93** [WebSystemsSolutions/opencart-rro-checkbox#1]
Ви структуру файлів для опенкарта 2.1 та 2.3 бачили? Вони різні, а у вас???
Цей модуль ніколи не буде працювати для 2.1.

**Comment by russellorv** [comment]
> Ви структуру файлів для опенкарта 2.1 та 2.3 бачили? Вони різні, а у вас???
> Цей модуль ніколи не буде працювати для 2.1.

Звісно ж бачили) модуль чудово працює як на 2.1 так і на 2.3
P.S: ніколи не кажіть ніколи)

**Comment by Stanislav93** [comment]
яка відмінність між 2.1  і  2.3?

**Comment by Stanislav93** [comment]
я два місяця як перевірив що модуль для 2.1 не працює.
А я займаюся написанням модулів, розробкою сайтів на базі опенкарта.
